name: CI

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

jobs:
  build:
    strategy:
      matrix:
        node-version: ['18.x', '19.x', '20.x']
    runs-on: ubuntu-latest
    container: node:latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci --dev

      - run: npx eslint .

        # - run: npm test

        env:
          CI: true
